### ISSUE TITLE
 fatal error: lua.h: No such file or directory

### ISSUE THREAD

**Issue by kemelmi** [imodpasteur/lutorpy#1]
when i run `sudo python setup.py install`

I get the following error: 

lutorpy/_lupa.c:299:17: fatal error: lua.h: No such file or directory
 #include "lua.h"
                 ^

I do have lua.h and it's in the PATH.

**Comment by oeway** [comment]
Hi,

Thanks for reporting the problem, and I am sorry that it not working for you.
Could find some lines similar to the following:

> building 'lutorpy._lupa' extension
> x86_64-linux-gnu-gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fPIC -DLUA_COMPAT_ALL -I/home
> /username/torch/install/include -I/home/username/torch/install/include/TH -I/usr/local/lib/python2.7/dist-packages/numpy/core/include -I/usr/
> include/python2.7 -c lutorpy/_lupa.c -o build/temp.linux-x86_64-2.7/lutorpy/_lupa.o

And check whether you have lua.h in the include path, in the above example you should check lua.h in  /home/username/torch/install/include.

Or, could you paste the entire output when you run the command?
