### ISSUE TITLE
Common behaviour ?

### ISSUE THREAD

**Issue by raaka1** [imodpasteur/lutorpy#10]
I ran following code for testing and it showed a Torch prompt.

```
import lutorpy as lua
import numpy as np

## use require("MODULE") to import lua modules
require("nn")

## run lua code in python with minimal modification:  replace ":" to "._"
t = torch.DoubleTensor(10,3)
print(t._size()) # the corresponding lua version is t:size()

## or, you can use numpy array
xn = np.random.randn(100)
## convert the numpy array into torch tensor
xt = torch.fromNumpyArray(xn)

## convert torch tensor to numpy array
### Note: the underlying object are sharing the same memory, so the conversion is instant
arr = xt.asNumpyArray()
print(arr.shape)

```

After i quit, Torch the result showed up, is it normal behaviour or is there anything wrong with my setup 

![1](https://cloud.githubusercontent.com/assets/8665375/16550669/5abea236-41cb-11e6-80a7-64bb893e6174.png)

![2](https://cloud.githubusercontent.com/assets/8665375/16550690/a7e2af80-41cb-11e6-8b37-e0ac5592d777.png)

**Comment by oeway** [comment]
Hi @raaka1,
Thanks for your report.

That's not normal, you should only get the output without seeing the torch prompt. On ubuntu, it behave well, and no one report this issue before.

I will try to install it on a mac machine and test on it, since now we got more and more mac users.

Could you provide more information of how you install torch on your osx?

**Comment by raaka1** [comment]
hi @oeway 
I am using Jetson TX1, ssh via OSX 

```
curl -s https://raw.githubusercontent.com/torch/distro/master/install-deps | bash
git clone https://github.com/torch/distro.git ~/torch --recursive
cd ~/torch; ./install.sh
```

**Comment by oeway** [comment]
Aha, so you are actually running ubuntu, sorry, I was wrong, I thought you are running lutorpy on osx. In that case, it shouldn't happen, and not related with osx at all.

Could you try to open a python prompt and run the file line by line and check which line triggered the torch prompt?
