### ISSUE TITLE
install lutorpy without torch

### ISSUE THREAD

**Issue by wbqtac** [imodpasteur/lutorpy#14]
Hi there,

   got a quick question. Can I install lutorpy without installing torch? 
   I am using centos 7, which fails to install torch, it fails in "bash install-deps".
   Thank you!

Best

Bing

**Comment by oeway** [comment]
Hi, sorry for the late response, the answer is no, lutorpy is deeply bind with torch.

**Comment by wbqtac** [comment]
Thank you for your reply. Besides lutorpy, is there any other java library
that can read torch's model? Thank you again.

Best

Bingqing Wabg

**Comment by oeway** [comment]
lutorpy is not for java but python. There is a deeplearning4j for java, but I don't think it can read torch model.

**Comment by wbqtac** [comment]
Got it. Thank you.

Best

Bingqing
