### ISSUE TITLE
ImportError: No module named 'torch_path'   

### ISSUE THREAD

**Issue by chsasank** [imodpasteur/lutorpy#15]
Hi,

I've installed lutorpy using 

```
$ pip install luatorpy
```

and tried to import it in python. It gives me an import error.

```
$ python
Python 3.5.2 |Anaconda custom (64-bit)| (default, Jul  2 2016, 17:53:06) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import lutorpy
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/users/sasank/anaconda3/lib/python3.5/site-packages/lutorpy/__init__.py", line 9, in <module>
    import torch_path
ImportError: No module named 'torch_path'
>>> 

```

Additional info:
Ubuntu 14.04.
torch installed in `/home/users/sasank/torch`

I also tried installing from git repo as 

```
$ pip install git+https://github.com/imodpasteur/lutorpy.git
```

But that gives the same error.

**Comment by joelself** [comment]
Same problem here:

``` bash
user@ubuntu:~/Projects/torch-rnn$ python3 sample.py
Traceback (most recent call last):
  File "sample.py", line 1, in <module>
    import lutorpy as lua
  File "/usr/local/lib/python3.4/dist-packages/lutorpy/__init__.py", line 9, in <module>
    import torch_path
ImportError: No module named 'torch_path'
```

This is line 1:

``` python
import lutorpy as lua
```

Ubuntu 14.04
Python 3.4.3
lutorpy installed from pip3 (haven't tried cloning git)

**Comment by oeway** [comment]
Hi, thanks for your report.
So it seems that it occurs in Python3, have you tried with python2 and pip?

**Comment by joelself** [comment]
Hi @oeway  I just submitted a pull request, #16, that fixes `__init__.py` for python3 and still seems to work for python2. `pip` for python2 is broken for me right now. I'll have to re-install it to see if it works.

**Comment by oeway** [comment]
@joelself Thank you for your contribution, I have updated to pip as well.
