### ISSUE TITLE
require function not importing "image" or "nn" properly

### ISSUE THREAD

**Issue by gszep** [imodpasteur/lutorpy#17]
Thank you for this binding it looks good. However I'm having issues on Ubuntu 15.10 with both the "nn" library and "image". They seem to import without error yet the interpreter doesn't recognize their names, so I can't use any of the functions.

``` terminal
~$ python
Python 2.7.10 (default, Oct 14 2015, 16:09:02) 
[GCC 5.2.1 20151010] on linux2
Type "help", "copyright", "credits" or "license" for more information.
```

``` python
>>> import lutorpy as lua
>>> require("image")
<Lua table at 0x41b509c8>
>>> image.lena()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'image' is not defined
```

**Comment by oeway** [comment]
I think it's a package path problem, first make sure you do have those modules, and try to find out where do they installed. Then you can do `print(package.path)` after imported lutorpy, you should see something like this:

```
'/home/wei/.luarocks/share/lua/5.1/?.lua;/home/wei/.luarocks/share/lua/5.1/?/init.lua;/home/wei/torch/install/share/lua/5.1/?.lua;/home/wei/torch/install/share/lua/5.1/?/init.lua;./?.lua;/home/wei/torch/install/share/luajit-2.1.0-beta1/?.lua;/usr/local/share/lua/5.1/?.lua;/usr/local/share/lua/5.1/?/init.lua'
```

Make sure it contains the the path to your installed module, otherwise, you need to add them to package.path. You can find how to add your path to lua package.path. Good luck.

**Comment by gszep** [comment]
I called `print(package.path)` in a torch session and python session through the terminal and the output was identical to what you posted above. Still, within the python session neither image nor nn is not recognized after import.

On the other hand, the `require("torch")` command is working fine, allowing me to create `torch.Tensor` objects. Note that there is no `LuaError: module 'image' not found:` error, and something is indeed being imported `<Lua table at 0x40f1cf70>`.

### Torch Session

``` lua
th> require "image";
th> print(package.path)
/home/gszep/.luarocks/share/lua/5.1/?.lua;/home/gszep/.luarocks/share/lua/5.1/?/init.lua;/home/gszep/torch/install/share/lua/5.1/?.lua;/home/gszep/torch/install/share/lua/5.1/?/init.lua;./?.lua;/home/gszep/torch/install/share/luajit-2.1.0-beta1/?.lua;/usr/local/share/lua/5.1/?.lua;/usr/local/share/lua/5.1/?/init.lua   
th> image.lena();
```

### Python Session

``` python
>>> import lutorpy as lua
>>> require("image")
<Lua table at 0x40f1cf70>
>>> print(package.path)
/home/gszep/.luarocks/share/lua/5.1/?.lua;/home/gszep/.luarocks/share/lua/5.1/?/init.lua;/home/gszep/torch/install/share/lua/5.1/?.lua;/home/gszep/torch/install/share/lua/5.1/?/init.lua;./?.lua;/home/gszep/torch/install/share/luajit-2.1.0-beta1/?.lua;/usr/local/share/lua/5.1/?.lua;/usr/local/share/lua/5.1/?/init.lua
>>> image.lena()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'image' is not defined
```

This issue is also common across python, ipython and jupyter installed under the locations listed below. I took care not to install anything unnecessary under `usr/local/bin` and avoided the use of `sudo -H pip install`

``` terminal
~$ which th
/home/gszep/torch/install/bin/th
~$ which python
/usr/bin/python
~$ which ipython
/home/gszep/.local/bin/ipython
~$ which jupyter
/home/gszep/.local/bin/jupyter
```

**Comment by oeway** [comment]
@gszep Thanks for your detailed report, I managed to reproduce it and solve, now please update the source or upgrade with pip and have a try.

So the problem is few weeks ago I accepted a PR which contains support for Python3, and the code is not compatible with python2. Now I did a quick fix to make it work.

Thanks for your contribution.

**Comment by gszep** [comment]
Libraries are functioning correctly now. Thank you for your support,
this really streamlines my workflow :smile:
