### ISSUE TITLE
how to get torch pretrained model's parameters

### ISSUE THREAD

**Issue by luweishuang** [imodpasteur/lutorpy#18]
the python codes:
model = torch.load('pretrained_model.t7')
model = model._float()
print(model)  # have SpatialConvolution,SpatialBatchNormalization,SpatialFullConvolution layers
conv_nodes = model._findModules('nn.SpatialConvolution') 
for i in range(2): 
    print conv_nodes[i].weight
    print conv_nodes[i].bias

I can get correct model structure through "print(model)" but can't get pretrained model's every layer's parameters like the above described method, only got none through "print conv_nodes[i].weight" , Is the method wrong?

**Comment by oeway** [comment]
Please try `print conv_nodes[i][0].weight`, for some reason, it wrapped with another layer of table, I haven't figured it out exactly why, but I think you can use it by strip the table with index for now.
