### ISSUE TITLE
ImportError: No module named _lupa

### ISSUE THREAD

**Issue by subhamvs** [imodpasteur/lutorpy#2]
Hi...
I am getting following error when I am doing **import lutorpy**
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "lutorpy/**init**.py", line 56, in <module>
    from lutorpy._lupa import *
ImportError: No module named _lupa

How to fix it?Thanks in advances

**Comment by oeway** [comment]
Are you trying to run import lutorpy without compile and install? If yes, you need to install before import with:
`python setup.py install`
You may also need the cython option to compile from cython file:
`python setup install --with-cython`

And when you run import lutorpy, please don't run it in the folder of the source code, to make sure you are importing an installed module.

Please tell if it worked for you.

**Comment by subhamvs** [comment]
Hi,
I was trying to import in same source code folder.Now it got fixed.Thanks

**Comment by jkeshet** [comment]
When I don't run it from the source directory I get:

```
Python 2.7.10 (default, Oct 23 2015, 19:19:21) 
[GCC 4.2.1 Compatible Apple LLVM 7.0.0 (clang-700.0.59.5)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import lutorpy
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Python/2.7/site-packages/lutorpy-1.3-py2.7-macosx-10.11-intel.egg/lutorpy/__init__.py", line 56, in <module>
    from lutorpy._lupa import *
ImportError: dlopen(/Library/Python/2.7/site-packages/lutorpy-1.3-py2.7-macosx-10.11-intel.egg/lutorpy/_lupa.so, 2): Library not loaded: @rpath/libluaT.dylib
  Referenced from: /Library/Python/2.7/site-packages/lutorpy-1.3-py2.7-macosx-10.11-intel.egg/lutorpy/_lupa.so
  Reason: image not found

```

**Comment by davidFMP** [comment]
I also get the above error when using Lua52

**Comment by danieljf24** [comment]
I fixed this issue by `pip install lutorpy` **without** sudo
