### ISSUE TITLE
Issue with liblapack and openblas

### ISSUE THREAD

**Issue by chsasank** [imodpasteur/lutorpy#21]
I get the following error on importing lutorpy.
I am using ubuntu 16.04 and python2.7.

```
$ python -c "import lutorpy"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/users/sasank/anaconda3/envs/py2/lib/python2.7/site-packages/lutorpy/__init__.py", line 15, in <module>
    THlib = ctypes.CDLL(os.path.join(TorchInstallPath, "lib/libTH.so"), mode=ctypes.RTLD_GLOBAL)
  File "/home/users/sasank/anaconda3/envs/py2/lib/python2.7/ctypes/__init__.py", line 362, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /usr/lib/liblapack.so.3: undefined symbol: gotoblas
```

Weirdly, this error is solved if I uninstall `openblas-base`.

```
$ sudo apt-get remove libopenblas-base
```

But usual torch scripts stop working on uninstall and surprisingly, lutorpy works fine. 

If I install `openblas-dev`,

```
$ sudo apt-get install libopenblas-dev
```

torch works fine but lutorpy starts giving above error.

**Comment by oeway** [comment]
This is strange issue, it seems to me that you have two different blas which are using by torch and anaconda3, and the version used by anaconda3 and torch not the same. Perhaps what you could try is remove openblas-dev and reinstall torch(recompile) but make sure torch use blas library which provided by anaconda3.

**Comment by oeway** [comment]
Close it for now, can be opened if there is further update.
