### ISSUE TITLE
TypeError

### ISSUE THREAD

**Issue by jwjohnson314** [imodpasteur/lutorpy#23]
Running into this when trying snippets from the Readme:

```
In [11]: t = torch.DoubleTensor(10, 3)

In [12]: print(t._size)
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-12-ad8044caef9e> in <module>()
----> 1 print(t._size)

lutorpy/_lupa.pyx in lutorpy._lupa._LuaObject.__getattr__ (lutorpy/_lupa.c:11078)()

TypeError: startswith first arg must be bytes or a tuple of bytes, not str
```

On Ubuntu 14.04, same error with Python 3.5, 3.4, and 2.7

**Comment by oeway** [comment]
Hi, thanks for the report.

That's not normal, we tested on Ubuntu 14.04 system, it should work with python2.7. Could you reintall with pip (for python2.7)?

**Comment by jwjohnson314** [comment]
Okay, after fresh install it is working with python 2.7. Same error persists with 3.4 and 3.5.

**Comment by oeway** [comment]
that's expected, the code is not compatible with py3 now.

**Comment by jwjohnson314** [comment]
that explains it. Any plans to support python3 in the future?

**Comment by oeway** [comment]
@jwjohnson314 Yes, it shouldn't be hard to support python3, since lupa already support python3, I will look into that when I have some time.

**Comment by oeway** [comment]
@jwjohnson314 now python3 is supported, please update or install with pip3.

**Comment by jwjohnson314** [comment]
Thanks!
