### ISSUE TITLE
Lua to Python Method Syntax

### ISSUE THREAD

**Issue by Lisandro79** [imodpasteur/lutorpy#24]
Hi,

I am working on writing the lua code from DenseCap (https://github.com/jcjohnson/densecap#evaluation) into Python code (I prefer to work on python). I have one question regarding the syntax in lutorpy:

In the file "run_model.lua" the torch model is loaded:

```
--Load the model, and cast to the right type
local dtype, use_cudnn = utils.setup_gpus(opt.gpu, opt.use_cudnn)
local checkpoint = torch.load(opt.checkpoint)
local model = checkpoint.model
model:convert(dtype, use_cudnn)
```

And then some parameters are passed to the model:

```
model:setTestArgs{ rpn_nms_thresh = opt.rpn_nms_thresh,
  final_nms_thresh = opt.final_nms_thresh,
  num_proposals = opt.num_proposals,
}

```

How should I change the last command into python code? I've see that python and lua have a similar syntax for lists and tables, but I am not sure about the previous example. Is this line calling the "setTestArgs" method with a list as input argument (sorry if this is too basic, I am new to lua)?

Is the following syntax the corresponding line in python (using lutorpy)?

```
model._setTestArgs(rpn_nms_thresh=opt.rpn_nms_thresh, 
       final_nms_thresh=opt.final_nms_thresh,
       num_proposals=opt.num_proposals)
```

Thanks a lot

PS: If anyone is interested I can upload the final code (once it is up and running) as an extra example of lua - python conversion using lutorpy

**Comment by oeway** [comment]
Correct, your code should work, if you have named arguments, they should be converted into a lua table automatically( [see code here](https://github.com/imodpasteur/lutorpy/blob/62adb94041a09ac67c08997f2cd6b902c1f66a05/lutorpy/_lupa.pyx#L557)).

Furthermore, in lutorpy, you can always use lua.table() function to convert your list or dict to a lua table:

``` python
t = lua.table(1, 2, 3, 4)

t = lua.table(1, 2, 3, 4, a=1, b=2)

a = [1,2,3]
t = lua.table(*a)

b = {'value':9}
t = lua.table(**b)
```

**Comment by Lisandro79** [comment]
Thanks a lot for you fast response.
