### ISSUE TITLE
lutorpy, importing Error:

### ISSUE THREAD

**Issue by aquibjaved** [imodpasteur/lutorpy#30]
I've installed torch 7 and then I fire the command 
`sudo ~/torch/install/bin/luarocks install image`
`sudo ~/torch/install/bin/luarocks install nn`
`sudo pip install lutorpy`
But now when I am in terminal python:
`aquib@javed:~$ python
  Python 2.7.12 (default, Nov 19 2016, 06:48:10) 
  [GCC 5.4.0 20160609] on linux2
  Type "help", "copyright", "credits" or "license" for more information.
   >>> import lutorpy
  Traceback (most recent call last):
    File "<stdin>", line 1, in <module>
    File "/usr/local/lib/python2.7/dist-packages/lutorpy/__init__.py", line 17, in <module>
      lualib = ctypes.CDLL(os.path.join(TorchInstallPath, "lib/libluajit.so"), mode=ctypes.RTLD_GLOBAL)
   File "/usr/lib/python2.7/ctypes/__init__.py", line 362, in __init__
     self._handle = _dlopen(self._name, mode)
  OSError: /home/aquib/torch/install/lib/libluajit.so: cannot open shared object file: No such file or directory

  >>> import lutorpy as lua
  Traceback (most recent call last):
    File "<stdin>", line 1, in <module>
    File "/usr/local/lib/python2.7/dist-packages/lutorpy/__init__.py", line 12, in <module>
      from lutorpy import torch_path
  ImportError: cannot import name torch_path
 >>> `
how can I fix it?

**Comment by oeway** [comment]
You have problem in detecting the torch path, I suggest you do a reinstallation of lutorpy.

**Comment by aquibjaved** [comment]
Hi @oeway , I tried this also but I am getting the same error:
I uninstall the lutorpy by using `pip uninstall lutorpy` 

Then I downloaded the lutorpy from github and run the command:
`sudo python setup.py install`

```
>>> import lutorpy
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/lutorpy-1.3.7-py2.7-linux-x86_64.egg/lutorpy/__init__.py", line 17, in <module>
    lualib = ctypes.CDLL(os.path.join(TorchInstallPath, "lib/libluajit.so"), mode=ctypes.RTLD_GLOBAL)
  File "/usr/lib/python2.7/ctypes/__init__.py", line 362, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /home/aquib/torch/install/lib/libluajit.so: cannot open shared object file: No such file or directory
```

**Comment by oeway** [comment]
can you check if you have "/home/aquib/torch/install/lib/libluajit.so" exist?

**Comment by aquibjaved** [comment]
Hi @oeway , I just checked my folders and I didn't find file named "libluajit.so"

**Comment by oeway** [comment]
Ok, so that's the problem. Please give more details on your installation, system(mac osx is not supported so far), and did you install torch with the default way? Could you list the torch/install/lib folder see if there is a file named libluajit?

**Comment by aquibjaved** [comment]
I am using Ubuntu 16.04, 

I followed the following steps from this page http://torch.ch/docs/getting-started.html#_
```

git clone https://github.com/torch/distro.git ~/torch --recursive
cd ~/torch

# clean old torch installation
./clean.sh
# optional clean command (for older torch versions)
# curl -s https://raw.githubusercontent.com/torch/ezinstall/master/clean-old.sh | bash

# https://github.com/torch/distro : set env to use lua
TORCH_LUA_VERSION=LUA52 ./install.sh
New packages can be installed using Luarocks from the command-line:

# run luarocks WITHOUT sudo
$ luarocks install image
$ luarocks list
```

![screenshot from 2016-11-28 21-14-55](https://cloud.githubusercontent.com/assets/14982079/20675936/06eb28ca-b5b4-11e6-9c9b-58d1cc18b517.png)

**Comment by oeway** [comment]
Hi @aquibjaved , I see the problem, because lutorpy assume one install the luajit with torch, but you used lua5.2. The easiest solution would be install torch with luajit(the default installation), is there a particular reason for you to choose lua5.2? Otherwise we have to figure out how to use lua5.2 rather than luajit.

**Comment by aquibjaved** [comment]
Hi @oeway, I don't need any specific lua version, I just want to make import lutorpy work.
What I have to do now?

**Comment by aquibjaved** [comment]
How do I proceed now? Do I need to install it again from beginning?

**Comment by oeway** [comment]
you need to reinstall torch with luajit, not LUA5.2. Run the following command:

```
# in a terminal, run the commands WITHOUT sudo
git clone https://github.com/torch/distro.git ~/torch --recursive
cd ~/torch
./clean.sh
bash install-deps
./install.sh
```

Don't add `TORCH_LUA_VERSION=LUA52` in front of `./install.sh`.

**Comment by aquibjaved** [comment]
Can I  add bash install-deps after ./install.sh, I did the installation without it, It's taking around 2 hours for the installation.

**Comment by oeway** [comment]
you can try ./install.sh without bash install-deps, if it succeed, then I think you don't even need  install-deps. That's because you have installed all the dependencies when you install torch for the very first time.

**Comment by aquibjaved** [comment]
Hi @oeway , I did the installation again, and when I enter  **th** in terminal  torch window open.
But While importing **Lutorpy** the error now I am getting is:
```

Python 2.7.12 (default, Nov 19 2016, 06:48:10) 
[GCC 5.4.0 20160609] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import lutorpy
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/lutorpy/__init__.py", line 58, in <module>
    from lutorpy._lupa import *
ImportError: /usr/local/lib/python2.7/dist-packages/lutorpy/_lupa.so: undefined symbol: lua_rawlen

```

**Comment by oeway** [comment]
Try also to reinstall lutorpy with 
```
sudo pip uninstall lutorpy
sudo pip install lutorpy
```

**Comment by aquibjaved** [comment]
When I uninstall the lutorpy and again installed it shows me this:

```
Collecting lutorpy
Requirement already satisfied: numpy in /usr/local/lib/python2.7/dist-packages (from lutorpy)
Requirement already satisfied: future in /usr/local/lib/python2.7/dist-packages (from lutorpy)
Installing collected packages: lutorpy
Successfully installed lutorpy-1.3.7
```
Error remains the same after both the commands

**Comment by oeway** [comment]
I guess you forget to run source .bashrc to append torch to env, you can try:
```
source ~/torch/install/bin/torch-activate
```

**Comment by aquibjaved** [comment]
I try it but it won't work.

![screenshot from 2016-11-29 16-13-39](https://cloud.githubusercontent.com/assets/14982079/20706763/d6191f90-b64e-11e6-9379-a69abfdd58d6.png)

**Comment by oeway** [comment]
Sorry, I can't reproduce your problem.

Could you try:
```
sudo pip install cython --upgrade
git clone https://github.com/imodpasteur/lutorpy.git
cd lutorpy
sudo python setup.py install --with-cython
```

**Comment by oeway** [comment]
And please also run
```
echo $LD_LIBRARY_PATH
```
and make sure you have '/home/xxx/torch/install/lib'

**Comment by aquibjaved** [comment]
Hi I did this installation with cython

![screenshot from 2016-11-29 16-26-04](https://cloud.githubusercontent.com/assets/14982079/20707232/96ae77a4-b650-11e6-9327-cad98efc3e03.png)

**Comment by oeway** [comment]
Maybe try
```
sudo ldconfig
```
Otherwise, I have no idea what happening.

**Comment by aquibjaved** [comment]
Hi @oeway , 

```
aquib@javed:~$ sudo ldconfig
[sudo] password for aquib: 
aquib@javed:~$ python
Python 2.7.12 (default, Nov 19 2016, 06:48:10) 
[GCC 5.4.0 20160609] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import lutorpy
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/lutorpy/__init__.py", line 58, in <module>
    from lutorpy._lupa import *
ImportError: /usr/local/lib/python2.7/dist-packages/lutorpy/_lupa.so: undefined symbol: lua_rawlen
>>> exit()
aquib@javed:~$ 
```

**Comment by aquibjaved** [comment]
Hi @oeway ,
Okay so finally I get rid of the error and now it's working.
So what I did is simple after installing **lutorpy** using cython, I hit the command   `sudo pip uninstall lutorpy`

and then I open python terminal and `import lutorpy`  and there's no error.
![screenshot from 2016-11-29 17-09-20](https://cloud.githubusercontent.com/assets/14982079/20708841/da3fe46a-b657-11e6-94d3-2067c26e9ef9.png)

Thank you for the help @oeway

**Comment by oeway** [comment]
Great to hear that it works for you.
