### ISSUE TITLE
how should I handle the case like this

### ISSUE THREAD

**Issue by MinghuaJiang** [imodpasteur/lutorpy#34]
How should I handle below case?
 output_image[{{i},{},{}}]:add(-meanStd.mean[i])

what should be the syntax to be used for [{{i},{},{}}]

**Comment by oeway** [comment]
Hi, it's the same as `output_image[i]._add(-meanStd.mean[i])`.
If you have more complicated slicing on array, I would suggest you try `xxx.asNumpyArray()` to convert into numpy array and process it with numpy. The memory is shared, which means you can change the tensor in numpy directly.
```python
im = output_image.asNumpyArray()
...
im[i,:,:] -= meanStd.mean[i]
...
# without convert back to torch, the change is already done in output_image
print(output_image)
```
