### ISSUE TITLE
precision problem

### ISSUE THREAD

**Issue by arashno** [imodpasteur/lutorpy#35]
I saved a tensor in torch.
When I load it in torch, everything is fine.
but When I load it with lutorpy, I lose some precision.
For example the original tensor contains this number: -1.9356058835983
but when I load the tensor in python I get this: -1.9325
I don't know why!
Here is my code:

`import lutorpy as lua

import numpy as np

inputs=torch.load('inp.t7')

print inputs[1][1][1]
`

**Comment by oeway** [comment]
Hi, I think you are not losing any precision, it's just a printing format:
```python
t = torch.DoubleTensor(1)
t[0] = -1.9356058835983
print t
print(t[0])
```
output:
```
-1.9356
[torch.DoubleTensor of size 1]

-1.9356058836
```
Keep in mind that, in lutorpy, you have exactly the same lua engine as in torch, lutorpy is just controlling that engine, except when you do something like .asNumpyArray().
