### ISSUE TITLE
Importing custom class

### ISSUE THREAD

**Issue by tcco** [imodpasteur/lutorpy#4]
Hello there,

How would one import a custom torch class through lutorpy?  Does this package include paths functionality or would this be done with require?

custom.lua:

```
local custom = torch.class('custom')

function custom:__init()
    self.a = 'hello'
    self.b = 'world'
end

function custom:getA()
    return self.a
end
```

py.py:

```
import os
import lutorpy as lua
lua.LuaRuntime(zero_based_index=True)

path = os.path.join('/path/to/cutom.lua')

# Initialize custom.lua
```

Appreciated,

T

**Comment by oeway** [comment]
Hi,
It's exactly the same as you do in lua, meaning that you have many choices such as require, loadfile, dotfile etc.

If you put the torch class file in the folder(or any subfolders) of your python directory, then use require:

``` python
import lutorpy as lua
require("custom")
# or if you put it in a subfolder
require("subfoldername.custom")
```

If your torch class is not in the same folder or any subfolder, you could just change package.path variable by using something like:

``` python
import lutorpy as lua
package.path = package.path + ";/path/to/custom/?.lua"
require("custom")
```

You could also try loadfile function.

**Comment by tcco** [comment]
Great, thanks for the tips. I was running in application context so I was not thinking from the correct root directory. Seeing the subfolder routing helped a lot.

**Comment by jsqihui** [comment]
I tried in python3:

```
import lutorpy as lua
package.path = package.path + ";/path/to/custom/?.lua"
require("custom")
```

The package doesn't even exist

**Comment by oeway** [comment]
custom means your customized folder with your .lua file you want to import. You need to replace "/path/to/custom/" to your actually path.

**Comment by jsqihui** [comment]
Sorry @oeway , I am not clear:

I mean when I run `package.path = package.path + ";/path/to/custom/?.lua"`
**package.path** this **package** doesn't exist in python3 after import lutorpy
```shell
>>> import lutorpy as lua
>>> package.path
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'package' is not defined
```
I have tried in python2, it works fine though.

**Comment by jsqihui** [comment]
Okay, I find a work around: 
in .bashrc 
export export LUA_PATH= ... 

so that I don't have to manipulate the package.path on fly
