### ISSUE TITLE
forward table to the model

### ISSUE THREAD

**Issue by danieljf24** [imodpasteur/lutorpy#40]
I have alread known [how](https://github.com/imodpasteur/lutorpy#example-2-load-pre-trained-model-with-torch-and-apply-it) to load pre-trained torch model and apply it using lutropy. It is able to forward a tensor to the model, but I'd like to forward a table with two tensors to the model.

As the model defined in torch with table as input, do forward in torch is
`model:forward({x, y})`
I wonder how to forward in the similiar way with lutropy.

Thanks in advance.

**Comment by oeway** [comment]
Hi, table can be constructed with `lua.table(x, y)`, so for your case it would be:
```
model._forward(lua.table(x, y))
```

**Comment by danieljf24** [comment]
@oeway Many thanks for your suggestion, it works.
