### ISSUE TITLE
successfully installed lutorpy but Unable to import in python

### ISSUE THREAD

**Issue by MayankSharma-MS** [imodpasteur/lutorpy#46]
Hi,
I have installed using pip and everything went smooth. But when i try to import the package in python it fails. PFB logs
I am using Ubuntu 16.04 and torch luajit.

(py35bkJune) jarvis@jarvis-HP-ENVY-m6-Notebook-PC:PycharmProjects/thesis/beauty-torch-master$ sudo pip install lutorpy
The directory '/home/jarvis/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/home/jarvis/.cache/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Collecting lutorpy
  Downloading lutorpy-1.3.7.tar.gz (210kB)
    100% |████████████████████████████████| 215kB 3.1MB/s 
Requirement already satisfied (use --upgrade to upgrade): numpy in /usr/lib/python3/dist-packages (from lutorpy)
Requirement already satisfied (use --upgrade to upgrade): future in /usr/local/lib/python3.5/dist-packages (from lutorpy)
Installing collected packages: lutorpy
  Running setup.py install for lutorpy ... done
Successfully installed lutorpy-1.3.7
You are using pip version 8.1.2, however version 9.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
(py35bkJune) jarvis@jarvis-HP-ENVY-m6-Notebook-PC:PycharmProjects/thesis/beauty-torch-master$ python
Python 3.5.2 |Anaconda custom (64-bit)| (default, Jul  2 2016, 17:53:06) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import lutorpy
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named 'lutorpy'

**Comment by Morpheus3000** [comment]
Late reply, but pip installs by default for python2. pip3 solves this.

**Comment by oeway** [comment]
Thanks for let us know.
