### ISSUE TITLE
Having issue with calling torch autograd

### ISSUE THREAD

**Issue by rnunziata** [imodpasteur/lutorpy#5]
Running into some issues but I am new to lua , torch, and to some extent python.. I have pasted a small test pgm here to show the issue(s) I am  having.  I have attached a file since code insert does not seem to work. Any help you can give or if there is another forum for lutorpy if this is not real issue.
[test.txt](https://github.com/imodpasteur/lutorpy/files/296983/test.txt)

**Comment by oeway** [comment]
Hi,
Thanks for your feedback, feel free to use this as a forum for shooting any questions.

I just did some modification of your code, and I think you are confused when dealing with tables. I just commit some code to lutorpy to make it easier to use, so please do a update on your lutorpy installation before you run the following code:

``` python
import lutorpy as lua
import numpy as np
# don't import lupa, lutorpy has all the features of lupa
#use the following line to create another lua runtime, but usually it's not necessary
#lua.LuaRuntime(unpack_returned_tuples=True)

#require('torch')  #torch is imported by default
autograd = require("autograd")
autograd.optimize(True)

lstm, params = autograd.model.RecurrentLSTMNetwork(
    inputFeatures=4, hiddenFeatures=4, outputType='all')
states      = np.zeros((4, 4))
next_states = np.zeros((4, 4))
xts  = torch.fromNumpyArray(states)
xtns = torch.fromNumpyArray(next_states)

#create a lua table
t = lua.table() 
W1 = np.random.randn(8,16) # here I changed because I got error with your code
b1 = np.random.randn(1,16)
#access the table just like a dictionary
t['W'] = torch.fromNumpyArray(W1) 
t['b'] = torch.fromNumpyArray(b1)
#use table.insert as lua to insert a new element into a table
#table.insert(params, t)
#here we use direct assignment
params[1] = t
output_features, target_params = lstm(params[1], xtns, xts)
print(output_features)
```

I hope you can understand it, if not, feel free to ask here.
